keys:
  - &primary age1dduyaqu5k47ldvfu09rsdr3zetghnxzd0v5delcxz94yl7vsvpaqlg6nxk
creation_rules: 
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/wg0.conf$
    key_groups:
    - age:
      - *primary
